### ISSUE TITLE
Much better documentation explains everything...

### ISSUE THREAD

**Issue by tam203** [informatics-lab/covid19-examples-and-docs#11]
Talking to Helen we really need to explain the data set in details and the computations/aggregations and how it all works.

Also keen to have 'errors' on any aggregations such as min, max, variation etc.

**Comment by tam203** [comment]
- [ ] Theo to upload the doc @maria-a62 has done to the blob

**Comment by tam203** [comment]
- [ ] Add wind
- [ ] shape file info coming soon
- [ ] Print as pdf and upload to blob... PDF int GItHub Docs page.

**Comment by maria-a62** [comment]
Document updated and pdf generated
[Covid-19 Data documentation.pdf](https://github.com/informatics-lab/covid19-examples-and-docs/files/4575603/Covid-19.Data.documentation.pdf)
Can Theo or Kevin upload to blob please

**Comment by kaedonkers** [comment]
Awesome work @maria-a62!

I have added the PDF to the data readme repo
-> https://github.com/informatics-lab/covid19-dataset-documentation/pull/3

**Comment by tam203** [comment]
I have added the uploading of this doc to the daily index and readme update. It just needs updating in [this repo](https://github.com/informatics-lab/covid19-dataset-documentation/blob/master/README_data_processing.pdf) to be synced up in with in 24h. I also updated the readme to reference it.
