### ISSUE TITLE
The index.html doesn't update automatically when the data is pushed

### ISSUE THREAD

**Issue by tam203** [informatics-lab/covid19-examples-and-docs#21]
The index.html (and README_data.md) is updated automatically on a push to master in the repo [covid19-dataset-documentation](https://github.com/informatics-lab/covid19-dataset-documentation)

It can be manually triggered from [Travis build page](https://travis-ci.com/github/informatics-lab/covid19-dataset-documentation)

This isn't ideal and is frequently out of sync.

**Comment by tam203** [comment]
Created a cron on Travis. This should run every 24 hours (but not at a set time). This should mean the index is only ever 24 hours out. Not ideal but ok for now...

**Comment by tam203** [comment]
![image](https://user-images.githubusercontent.com/1567535/80601355-9b2c0d80-8a25-11ea-91b8-feeb6b0933a6.png)

**Comment by tam203** [comment]
@kaedonkers @DPeterK @maria-a62 FYI see this issue or don't. TLDR; the updating of the `index.html` page should be on a cron that runs every 24 hours (but not at a particular time). You can still manually trigger a build to update. The is managed by Travis.

Not ideal but good enough.

**Comment by kaedonkers** [comment]
Nice one theo!
