### ISSUE TITLE
Prep data and README.md to release on microsoft open data sets.

### ISSUE THREAD

**Issue by tam203** [informatics-lab/covid19-examples-and-docs#8]
To get this on the MS opendata sets we need to ensure we address all these questions below in the READ ME. 
 

> What format is your data in? (parquet, csv, image, files)
> 
>  
> 
>  
> 
> Also please make sure that you upload both zipped (for folks who want to download) and unzipped (for folks who want to mount and use the dataset directly on Azure compute) versions of the dataset. Let us know if you need help or have any questions.
> 
>  
> 
> We also require the following files from you :
> 
>  
> 
- [x]  Overview mark down file
- [x]  Introduction
- [x]  Information about the dataset and data, who collected the data, how, and why.
- [x]  Volume and retention
- [x]  file format, how often the dataset will be updated, how many rows, dataset size (mb/gb), etc.
- [x]  Storage Location
- [x]   Ex. East US  or West US.
> Additional information
- [x]  Links to raw dataset - a link back to the where the raw data is located (ex. your Github).
- [x]  Contact information (email) for users to reach out to the data owner if they have additional questions about the dataset.
- [x]  Licensing information – links to the licenses.
- [x]  Any other information you wish for users to know
>  
> 

- [x] Python sample notebooks that demonstrate how to access the data from the Azure storage
> Accessing the data and doing data manipulations to shows different ways in which the data can be used

>  
> 
> Attached you will find a file containing example files of the above information. The example files are of our NOAA ISD weather dataset: https://azure.microsoft.com/en-us/services/open-datasets/catalog/noaa-integrated-surface-data/
> 
>  
> 
> If you have any questions please feel free to reach out to us.
> 
>  
> 
> We look forward to working with you,
> 
>  
> 
> Thanks,
> 
> Rashaud

**Comment by tam203** [comment]
@kaedonkers assigning to you. Partly because you are readme master but also because I want to test the project tools.

**Comment by kaedonkers** [comment]
👍

*---------------------------------------------------------------*

*Kevin Donkers, MSci*
Technologist

Met Office Informatics Lab



www.informaticslab.co.uk

Met Office HPC Complex, Upper Richardson,

Science Park, Exeter, EX5 2FS

United Kingdom



Please send all officially sensitive info to:

kevin.donkers@metoffice.gov.uk

(and please let me know you've sent it!)
